artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/InsightfulCoderDivine/End-To-End-Machine-Learning-Project-with-MlFlow/raw/refs/heads/main/loan%20default%20data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/Loan_Default.csv
  STATUS_FILE: artifacts/data_validation/status.txt

handle_missing_values:
  root_dir: artifacts/handle_missing_values
  unzip_data_dir: artifacts/data_ingestion/Loan_Default.csv
  cleaned_data_dir: artifacts/handle_missing_values/Cleaned_Loan_Default.csv
  STATUS_FILE: artifacts/handle_missing_values/status.txt

data_manipulation:
  root_dir: artifacts/data_manipulation
  cleaned_data_dir: artifacts/handle_missing_values/Cleaned_Loan_Default.csv
  manipulated_data_dir: artifacts/data_manipulation/Manipulated_Loan_Default.csv
  STATUS_FILE: artifacts/data_manipulation/status.txt

